export type PhbGearCategory = "gear" | "tool" | "pack" | "other";

export type PhbGearItem = {
  id: string;
  nameRu: string;
  costCp: number;
  weightLb: number;
  category: PhbGearCategory;
};

/** PHB «Снаряжение искателя приключений» (без оружия и доспехов). Цены в медных монетах. */
export const PHB_GEAR_CATALOG: readonly PhbGearItem[] = [
  { id: "abacus", nameRu: "Счёты", costCp: 200, weightLb: 2, category: "gear" },
  { id: "acid", nameRu: "Кислота (флакон)", costCp: 2500, weightLb: 1, category: "gear" },
  {
    id: "alchemists-fire",
    nameRu: "Алхимический огонь (флакон)",
    costCp: 5000,
    weightLb: 1,
    category: "gear",
  },
  { id: "antitoxin", nameRu: "Противоядие (флакон)", costCp: 5000, weightLb: 0, category: "gear" },
  {
    id: "arcane-focus-crystal",
    nameRu: "Магическая фокусировка (кристалл)",
    costCp: 1000,
    weightLb: 1,
    category: "gear",
  },
  {
    id: "arcane-focus-orb",
    nameRu: "Магическая фокусировка (сфера)",
    costCp: 2000,
    weightLb: 3,
    category: "gear",
  },
  {
    id: "arcane-focus-rod",
    nameRu: "Магическая фокусировка (жезл)",
    costCp: 1000,
    weightLb: 1,
    category: "gear",
  },
  {
    id: "arcane-focus-staff",
    nameRu: "Магическая фокусировка (посох)",
    costCp: 500,
    weightLb: 4,
    category: "gear",
  },
  {
    id: "arcane-focus-wand",
    nameRu: "Магическая фокусировка (волшебная палочка)",
    costCp: 1000,
    weightLb: 1,
    category: "gear",
  },
  { id: "backpack", nameRu: "Рюкзак", costCp: 200, weightLb: 5, category: "pack" },
  {
    id: "ball-bearings",
    nameRu: "Шарики подшипников (мешок из 1000)",
    costCp: 100,
    weightLb: 2,
    category: "gear",
  },
  { id: "barrel", nameRu: "Бочка", costCp: 200, weightLb: 70, category: "gear" },
  { id: "basket", nameRu: "Корзина", costCp: 40, weightLb: 2, category: "gear" },
  { id: "bedroll", nameRu: "Спальный мешок", costCp: 100, weightLb: 7, category: "gear" },
  { id: "bell", nameRu: "Колокольчик", costCp: 100, weightLb: 0, category: "gear" },
  { id: "blanket", nameRu: "Одеяло", costCp: 50, weightLb: 3, category: "gear" },
  { id: "block-and-tackle", nameRu: "Полиспаст", costCp: 100, weightLb: 5, category: "gear" },
  { id: "book", nameRu: "Книга", costCp: 2500, weightLb: 5, category: "gear" },
  { id: "bottle-glass", nameRu: "Бутыль (стекло)", costCp: 200, weightLb: 2, category: "gear" },
  { id: "bucket", nameRu: "Ведро", costCp: 5, weightLb: 2, category: "gear" },
  { id: "caltrops", nameRu: "Шипы (мешок из 20)", costCp: 100, weightLb: 2, category: "gear" },
  { id: "candle", nameRu: "Свеча", costCp: 1, weightLb: 0, category: "gear" },
  { id: "case-map", nameRu: "Футляр для карт или свитков", costCp: 100, weightLb: 1, category: "gear" },
  { id: "chain", nameRu: "Цепь (10 футов)", costCp: 500, weightLb: 10, category: "gear" },
  { id: "chalk", nameRu: "Мел (1 штука)", costCp: 1, weightLb: 0, category: "gear" },
  { id: "chest", nameRu: "Сундук", costCp: 500, weightLb: 25, category: "gear" },
  { id: "climbers-kit", nameRu: "Набор альпиниста", costCp: 2500, weightLb: 12, category: "pack" },
  {
    id: "clothes-common",
    nameRu: "Комплект простой одежды",
    costCp: 50,
    weightLb: 3,
    category: "gear",
  },
  {
    id: "clothes-costume",
    nameRu: "Костюм",
    costCp: 500,
    weightLb: 4,
    category: "gear",
  },
  {
    id: "clothes-fine",
    nameRu: "Комплект нарядной одежды",
    costCp: 1500,
    weightLb: 6,
    category: "gear",
  },
  {
    id: "clothes-travelers",
    nameRu: "Комплект дорожной одежды",
    costCp: 200,
    weightLb: 4,
    category: "gear",
  },
  {
    id: "component-pouch",
    nameRu: "Мешочек с компонентами",
    costCp: 2500,
    weightLb: 2,
    category: "gear",
  },
  { id: "crowbar", nameRu: "Ломик", costCp: 200, weightLb: 5, category: "tool" },
  { id: "druidic-focus", nameRu: "Фокусировка друида", costCp: 500, weightLb: 0, category: "gear" },
  { id: "fishing-tackle", nameRu: "Рыболовные снаряды", costCp: 100, weightLb: 4, category: "tool" },
  { id: "flask-tankard", nameRu: "Фляга или кружка", costCp: 2, weightLb: 1, category: "gear" },
  { id: "grappling-hook", nameRu: "Крюк-кошка", costCp: 200, weightLb: 4, category: "gear" },
  { id: "hammer", nameRu: "Молоток", costCp: 100, weightLb: 3, category: "tool" },
  { id: "healers-kit", nameRu: "Набор целителя", costCp: 500, weightLb: 3, category: "pack" },
  { id: "holy-symbol", nameRu: "Священный символ", costCp: 500, weightLb: 0, category: "gear" },
  { id: "holy-water", nameRu: "Святая вода (флакон)", costCp: 2500, weightLb: 1, category: "gear" },
  { id: "hourglass", nameRu: "Песочные часы", costCp: 2500, weightLb: 1, category: "gear" },
  { id: "hunting-trap", nameRu: "Охотничья силок", costCp: 500, weightLb: 25, category: "gear" },
  { id: "ink-bottle", nameRu: "Бутыль чёрных чернил", costCp: 1000, weightLb: 0, category: "gear" },
  { id: "ink-pen", nameRu: "Перо", costCp: 2, weightLb: 0, category: "gear" },
  { id: "jug-pitcher", nameRu: "Кувшин", costCp: 2, weightLb: 4, category: "gear" },
  { id: "ladder", nameRu: "Лестница (10 футов)", costCp: 10, weightLb: 25, category: "gear" },
  { id: "lamp", nameRu: "Лампа", costCp: 50, weightLb: 1, category: "gear" },
  {
    id: "lantern-bullseye",
    nameRu: "Фонарь прожекторный",
    costCp: 1000,
    weightLb: 2,
    category: "gear",
  },
  {
    id: "lantern-hooded",
    nameRu: "Фонарь закрытый",
    costCp: 500,
    weightLb: 2,
    category: "gear",
  },
  { id: "lock", nameRu: "Замок", costCp: 1000, weightLb: 1, category: "tool" },
  {
    id: "magnifying-glass",
    nameRu: "Увеличительное стекло",
    costCp: 10000,
    weightLb: 0,
    category: "gear",
  },
  { id: "manacles", nameRu: "Кандалы", costCp: 200, weightLb: 6, category: "gear" },
  { id: "mess-kit", nameRu: "Походная посуда", costCp: 20, weightLb: 1, category: "pack" },
  { id: "mirror-steel", nameRu: "Зеркало стальное", costCp: 500, weightLb: 0.5, category: "gear" },
  { id: "oil-flask", nameRu: "Масло (флакон)", costCp: 10, weightLb: 1, category: "gear" },
  { id: "paper-sheet", nameRu: "Лист бумаги", costCp: 20, weightLb: 0, category: "gear" },
  { id: "parchment-sheet", nameRu: "Лист пергамента", costCp: 10, weightLb: 0, category: "gear" },
  { id: "perfume", nameRu: "Духи (флакон)", costCp: 500, weightLb: 0, category: "gear" },
  { id: "pick-miners", nameRu: "Кирка", costCp: 200, weightLb: 10, category: "tool" },
  { id: "piton", nameRu: "Скальные крюкья (10 штук)", costCp: 5, weightLb: 2.5, category: "gear" },
  { id: "poison-basic", nameRu: "Яд простой (флакон)", costCp: 10000, weightLb: 0, category: "gear" },
  { id: "pole", nameRu: "Шест (10 футов)", costCp: 5, weightLb: 7, category: "gear" },
  { id: "pot-iron", nameRu: "Чугунный котёл", costCp: 200, weightLb: 10, category: "gear" },
  {
    id: "potion-of-healing",
    nameRu: "Зелье лечения",
    costCp: 5000,
    weightLb: 0.5,
    category: "gear",
  },
  { id: "pouch", nameRu: "Кошелёк", costCp: 50, weightLb: 1, category: "gear" },
  { id: "quiver", nameRu: "Колчан", costCp: 100, weightLb: 1, category: "gear" },
  { id: "ram-portable", nameRu: "Таран переносной", costCp: 400, weightLb: 35, category: "gear" },
  { id: "rations", nameRu: "Паёк (1 день)", costCp: 50, weightLb: 2, category: "gear" },
  { id: "robes", nameRu: "Облачение", costCp: 100, weightLb: 4, category: "gear" },
  { id: "rope-hempen", nameRu: "Верёвка пеньковая (50 футов)", costCp: 100, weightLb: 10, category: "gear" },
  { id: "rope-silk", nameRu: "Шёлковая верёвка (50 футов)", costCp: 1000, weightLb: 5, category: "gear" },
  { id: "sack", nameRu: "Мешок", costCp: 1, weightLb: 0.5, category: "gear" },
  { id: "scale-merchants", nameRu: "Весы торговые", costCp: 500, weightLb: 3, category: "tool" },
  { id: "sealing-wax", nameRu: "Сургуч", costCp: 50, weightLb: 0, category: "gear" },
  { id: "shovel", nameRu: "Лопата", costCp: 200, weightLb: 5, category: "tool" },
  { id: "signal-whistle", nameRu: "Сигнальный свисток", costCp: 5, weightLb: 0, category: "gear" },
  { id: "signet-ring", nameRu: "Печатка", costCp: 500, weightLb: 0, category: "gear" },
  { id: "soap", nameRu: "Мыло", costCp: 2, weightLb: 0, category: "gear" },
  { id: "spellbook", nameRu: "Книга заклинаний", costCp: 5000, weightLb: 3, category: "gear" },
  { id: "spikes-iron", nameRu: "Железные шипы (10 штук)", costCp: 100, weightLb: 5, category: "gear" },
  { id: "spyglass", nameRu: "Подзорная труба", costCp: 100000, weightLb: 1, category: "gear" },
  { id: "tent-two-person", nameRu: "Палатка (на двоих)", costCp: 200, weightLb: 20, category: "gear" },
  { id: "tinderbox", nameRu: "Огнива", costCp: 50, weightLb: 1, category: "gear" },
  { id: "torch", nameRu: "Факел", costCp: 1, weightLb: 1, category: "gear" },
  { id: "vial", nameRu: "Пробирка", costCp: 100, weightLb: 0, category: "gear" },
  { id: "waterskin", nameRu: "Бурдюк", costCp: 20, weightLb: 5, category: "gear" },
  { id: "winter-blanket", nameRu: "Зимнее одеяло", costCp: 50, weightLb: 3, category: "gear" },
  {
    id: "herbalism-kit",
    nameRu: "Набор травника",
    costCp: 500,
    weightLb: 3,
    category: "tool",
  },
  {
    id: "disguise-kit",
    nameRu: "Набор для маскировки",
    costCp: 2500,
    weightLb: 3,
    category: "tool",
  },
] as const;

const gearById = new Map<string, PhbGearItem>(
  PHB_GEAR_CATALOG.map((item) => [item.id, item]),
);

export function getPhbGearItem(id: string): PhbGearItem | undefined {
  return gearById.get(id);
}
