export type PhbWeapon = {
  id: string;
  nameRu: string;
  costCp: number;
  weightLb: number;
  damage: string;
  damageTypeRu: string;
  propertiesRu: string[];
  category: "simple" | "martial";
  melee: boolean;
  finesse: boolean;
  ranged: boolean;
};

/** PHB оружие (~35 позиций). Цены в медных монетах. */
export const PHB_WEAPONS_CATALOG: readonly PhbWeapon[] = [
  {
    id: "club",
    nameRu: "Дубинка",
    costCp: 10,
    weightLb: 2,
    damage: "1d4",
    damageTypeRu: "дробящий",
    propertiesRu: ["лёгкое"],
    category: "simple",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "dagger",
    nameRu: "Кинжал",
    costCp: 200,
    weightLb: 1,
    damage: "1d4",
    damageTypeRu: "колющий",
    propertiesRu: ["фехтовальное", "лёгкое", "метательное (20/60)"],
    category: "simple",
    melee: true,
    finesse: true,
    ranged: false,
  },
  {
    id: "greatclub",
    nameRu: "Палица",
    costCp: 20,
    weightLb: 10,
    damage: "1d8",
    damageTypeRu: "дробящий",
    propertiesRu: ["двуручное"],
    category: "simple",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "handaxe",
    nameRu: "Ручной топор",
    costCp: 500,
    weightLb: 2,
    damage: "1d6",
    damageTypeRu: "рубящий",
    propertiesRu: ["лёгкое", "метательное (20/60)"],
    category: "simple",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "javelin",
    nameRu: "Метательное копьё",
    costCp: 50,
    weightLb: 2,
    damage: "1d6",
    damageTypeRu: "колющий",
    propertiesRu: ["метательное (30/120)"],
    category: "simple",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "light-hammer",
    nameRu: "Лёгкий молот",
    costCp: 200,
    weightLb: 2,
    damage: "1d4",
    damageTypeRu: "дробящий",
    propertiesRu: ["лёгкое", "метательное (20/60)"],
    category: "simple",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "mace",
    nameRu: "Булава",
    costCp: 500,
    weightLb: 4,
    damage: "1d6",
    damageTypeRu: "дробящий",
    propertiesRu: [],
    category: "simple",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "quarterstaff",
    nameRu: "Посох",
    costCp: 20,
    weightLb: 4,
    damage: "1d6",
    damageTypeRu: "дробящий",
    propertiesRu: ["универсальное (1d8)"],
    category: "simple",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "sickle",
    nameRu: "Серп",
    costCp: 100,
    weightLb: 2,
    damage: "1d4",
    damageTypeRu: "рубящий",
    propertiesRu: ["лёгкое"],
    category: "simple",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "spear",
    nameRu: "Копьё",
    costCp: 100,
    weightLb: 3,
    damage: "1d6",
    damageTypeRu: "колющий",
    propertiesRu: ["метательное (20/60)", "универсальное (1d8)"],
    category: "simple",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "light-crossbow",
    nameRu: "Арбалет, лёгкий",
    costCp: 2500,
    weightLb: 5,
    damage: "1d8",
    damageTypeRu: "колющий",
    propertiesRu: ["боеприпасы (80/320)", "зарядка", "двуручное"],
    category: "simple",
    melee: false,
    finesse: false,
    ranged: true,
  },
  {
    id: "dart",
    nameRu: "Дротик",
    costCp: 5,
    weightLb: 0.25,
    damage: "1d4",
    damageTypeRu: "колющий",
    propertiesRu: ["фехтовальное", "метательное (20/60)"],
    category: "simple",
    melee: false,
    finesse: true,
    ranged: true,
  },
  {
    id: "shortbow",
    nameRu: "Короткий лук",
    costCp: 2500,
    weightLb: 2,
    damage: "1d6",
    damageTypeRu: "колющий",
    propertiesRu: ["боеприпасы (80/320)", "двуручное"],
    category: "simple",
    melee: false,
    finesse: false,
    ranged: true,
  },
  {
    id: "sling",
    nameRu: "Праща",
    costCp: 10,
    weightLb: 0,
    damage: "1d4",
    damageTypeRu: "дробящий",
    propertiesRu: ["боеприпасы (30/120)"],
    category: "simple",
    melee: false,
    finesse: false,
    ranged: true,
  },
  {
    id: "battleaxe",
    nameRu: "Боевой топор",
    costCp: 1000,
    weightLb: 4,
    damage: "1d8",
    damageTypeRu: "рубящий",
    propertiesRu: ["универсальное (1d10)"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "flail",
    nameRu: "Цеп",
    costCp: 1000,
    weightLb: 2,
    damage: "1d8",
    damageTypeRu: "дробящий",
    propertiesRu: [],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "glaive",
    nameRu: "Глефа",
    costCp: 2000,
    weightLb: 6,
    damage: "1d10",
    damageTypeRu: "рубящий",
    propertiesRu: ["тяжёлое", "длинное", "двуручное"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "greataxe",
    nameRu: "Секира",
    costCp: 3000,
    weightLb: 7,
    damage: "1d12",
    damageTypeRu: "рубящий",
    propertiesRu: ["тяжёлое", "двуручное"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "greatsword",
    nameRu: "Двуручный меч",
    costCp: 5000,
    weightLb: 6,
    damage: "2d6",
    damageTypeRu: "рубящий",
    propertiesRu: ["тяжёлое", "двуручное"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "halberd",
    nameRu: "Алебарда",
    costCp: 2000,
    weightLb: 6,
    damage: "1d10",
    damageTypeRu: "рубящий",
    propertiesRu: ["тяжёлое", "длинное", "двуручное"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "lance",
    nameRu: "Копьё рыцаря",
    costCp: 1000,
    weightLb: 6,
    damage: "1d12",
    damageTypeRu: "колющий",
    propertiesRu: ["длинное", "особое"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "longsword",
    nameRu: "Длинный меч",
    costCp: 1500,
    weightLb: 3,
    damage: "1d8",
    damageTypeRu: "рубящий",
    propertiesRu: ["универсальное (1d10)"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "maul",
    nameRu: "Молот",
    costCp: 1000,
    weightLb: 10,
    damage: "2d6",
    damageTypeRu: "дробящий",
    propertiesRu: ["тяжёлое", "двуручное"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "morningstar",
    nameRu: "Моргенштерн",
    costCp: 1500,
    weightLb: 4,
    damage: "1d8",
    damageTypeRu: "колющий",
    propertiesRu: [],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "pike",
    nameRu: "Пика",
    costCp: 500,
    weightLb: 18,
    damage: "1d10",
    damageTypeRu: "колющий",
    propertiesRu: ["тяжёлое", "длинное", "двуручное"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "rapier",
    nameRu: "Рапира",
    costCp: 2500,
    weightLb: 2,
    damage: "1d8",
    damageTypeRu: "колющий",
    propertiesRu: ["фехтовальное"],
    category: "martial",
    melee: true,
    finesse: true,
    ranged: false,
  },
  {
    id: "scimitar",
    nameRu: "Скимитар",
    costCp: 2500,
    weightLb: 3,
    damage: "1d6",
    damageTypeRu: "рубящий",
    propertiesRu: ["фехтовальное", "лёгкое"],
    category: "martial",
    melee: true,
    finesse: true,
    ranged: false,
  },
  {
    id: "shortsword",
    nameRu: "Короткий меч",
    costCp: 1000,
    weightLb: 2,
    damage: "1d6",
    damageTypeRu: "колющий",
    propertiesRu: ["фехтовальное", "лёгкое"],
    category: "martial",
    melee: true,
    finesse: true,
    ranged: false,
  },
  {
    id: "trident",
    nameRu: "Трезубец",
    costCp: 500,
    weightLb: 4,
    damage: "1d6",
    damageTypeRu: "колющий",
    propertiesRu: ["метательное (20/60)", "универсальное (1d8)"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "war-pick",
    nameRu: "Боевой кирок",
    costCp: 500,
    weightLb: 2,
    damage: "1d8",
    damageTypeRu: "колющий",
    propertiesRu: [],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "warhammer",
    nameRu: "Боевой молот",
    costCp: 1500,
    weightLb: 2,
    damage: "1d8",
    damageTypeRu: "дробящий",
    propertiesRu: ["универсальное (1d10)"],
    category: "martial",
    melee: true,
    finesse: false,
    ranged: false,
  },
  {
    id: "whip",
    nameRu: "Кнут",
    costCp: 200,
    weightLb: 3,
    damage: "1d4",
    damageTypeRu: "рубящий",
    propertiesRu: ["фехтовальное", "длинное"],
    category: "martial",
    melee: true,
    finesse: true,
    ranged: false,
  },
  {
    id: "hand-crossbow",
    nameRu: "Арбалет, ручной",
    costCp: 7500,
    weightLb: 3,
    damage: "1d6",
    damageTypeRu: "колющий",
    propertiesRu: ["боеприпасы (30/120)", "лёгкое", "зарядка"],
    category: "martial",
    melee: false,
    finesse: false,
    ranged: true,
  },
  {
    id: "heavy-crossbow",
    nameRu: "Арбалет, тяжёлый",
    costCp: 5000,
    weightLb: 18,
    damage: "1d10",
    damageTypeRu: "колющий",
    propertiesRu: ["боеприпасы (100/400)", "тяжёлое", "зарядка", "двуручное"],
    category: "martial",
    melee: false,
    finesse: false,
    ranged: true,
  },
  {
    id: "longbow",
    nameRu: "Длинный лук",
    costCp: 5000,
    weightLb: 2,
    damage: "1d8",
    damageTypeRu: "колющий",
    propertiesRu: ["боеприпасы (150/600)", "тяжёлое", "двуручное"],
    category: "martial",
    melee: false,
    finesse: false,
    ranged: true,
  },
];

const weaponsById = new Map(PHB_WEAPONS_CATALOG.map((weapon) => [weapon.id, weapon]));

const weaponsByNameRu = new Map(
  PHB_WEAPONS_CATALOG.map((weapon) => [weapon.nameRu.toLowerCase(), weapon]),
);

export function getPhbWeapon(id: string): PhbWeapon | undefined {
  return weaponsById.get(id);
}

/** Match inventory row to PHB weapon by catalogId or exact Russian name. */
export function resolveInventoryWeapon(item: {
  catalogId: string | null;
  nameRu: string;
}): PhbWeapon | undefined {
  if (item.catalogId) {
    const byId = getPhbWeapon(item.catalogId);
    if (byId) {
      return byId;
    }
  }

  return weaponsByNameRu.get(item.nameRu.toLowerCase());
}

/** Unique weapons recognized in inventory (first occurrence per weapon id). */
export function getInventoryWeapons(
  inventory: ReadonlyArray<{ catalogId: string | null; nameRu: string }>,
): PhbWeapon[] {
  const seen = new Set<string>();
  const weapons: PhbWeapon[] = [];

  for (const item of inventory) {
    const weapon = resolveInventoryWeapon(item);
    if (weapon && !seen.has(weapon.id)) {
      seen.add(weapon.id);
      weapons.push(weapon);
    }
  }

  return weapons;
}
